homework 7
psergeev/react-hw pull request #5
Opened 2019-03-31 20:12 UTC by psergeev

2019-04-09 13:16 UTC, loginov-rocks requested changes

2019-04-09 13:16 UTC, loginov-rocks commented on src/components/App/App.tsx
> +                <this.props.Router location={this.props.location}>
My eyes are bleeding.

2019-04-09 13:16 UTC, loginov-rocks commented on src/components/HeaderWithDetails/HeaderWithDetails.tsx
> +    public componentWillMount() {
Deprecated https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

2019-04-09 13:16 UTC, loginov-rocks commented on src/components/HeaderWithSearch/HeaderWithSearch.tsx
> +    public componentWillMount() {
Deprecated https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

2019-04-09 13:17 UTC, loginov-rocks commented
Cypress broken?

<img width="500" alt="Screen Shot 2019-04-09 at 4 16 17 PM" src="https://user-images.githubusercontent.com/8770338/55803386-e43fb580-5ae2-11e9-8963-659a117169bf.png">

2019-04-09 13:19 UTC, loginov-rocks commented
Fetching for http://localhost:8000/search/star%20wars results into:

```html
<div id="app"><main><section class="results"><div class="results-sorter"><div class="hidden"><div>0 movie(s) found</div><div><span>Sort by</span><a href="#" class="sort-by-button ">release date</a><a href="#" class="sort-by-button selected">rating</a></div></div></div></section><footer>netflixroulette</footer></main></div>
                <script>
                    window.PRELOADED_STATE = {"prevMovies":[],"movies":[],"isEmpty":true,"search":"","searchBy":"title","sortBy":"rating","selectedMovie":null}
                </script>
```

So it does not seem to make any requests from the server side, right?

2019-04-09 13:31 UTC, loginov-rocks commented on src/components/App/App.tsx
> +const AsyncHeaderWithSearch = loadable(() => import('../HeaderWithSearch'));
This part and the following line doesn't work as expected, please check loadable imports.

2019-04-15 19:22 UTC, psergeev commented on src/components/App/App.tsx
> +                <this.props.Router location={this.props.location}>
fixed

2019-04-15 19:23 UTC, psergeev commented on src/components/HeaderWithDetails/HeaderWithDetails.tsx
> +    public componentWillMount() {
moved into constructor

2019-04-15 19:23 UTC, psergeev commented on src/components/HeaderWithSearch/HeaderWithSearch.tsx
> +    public componentWillMount() {
moved into constructor

2019-04-15 19:23 UTC, psergeev commented on src/components/App/App.tsx
> +const AsyncHeaderWithSearch = loadable(() => import('../HeaderWithSearch'));
fixed

2019-04-16 04:36 UTC, loginov-rocks approved these changes
LGTM

2019-04-16 05:09 UTC, merged